### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by gsganden**

### CODE REVIEW

**Review by philtrade — CHANGES_REQUESTED** [review]
Hi Greg,

Thank you for suggesting the PR, appreciate it!

While it's a reasonable measure, I also wonder about doing the check inside the code, to avoid using the `cluster-id` if the version is 6.2.5 or above.  I prefer not requiring users to using certain version of older libraries, as it's a nightmare for users to keep track.

i.e.g the 'pillow < 7' thing was due to when `fastai v1` had breakage with pillow v7, which is almost all fixed by now, then all dependent packages' `setup.py` need to be updated again.

I can merge this in for now, until a proper fix in the code is put in at a later time.

By the way, do you mind keeping the `install_requires` list to a single line?  I prefer fewer lines for ease of reading (less scrolling needed).  Thank you!

**Comment by gsganden** [comment]
Maybe `!=6.2.5` is a better option than `<6.2.5`, assuming that they fix the problem? That way the downstream impact is limited. Personally I wouldn't want to have workarounds in the code for bugs in specific dependency versions, but it's your library!

> By the way, do you mind keeping the install_requires list to a single line? I prefer fewer lines for ease of reading (less scrolling needed). Thank you!

Your call. One advantage of breaking across multiple lines is that it is convenient for commenting on why a version is pinned, which is helpful for knowing what pinning you might be able to undo later.

**Comment by philtrade** [comment]
Ha, I didn't know != is an accepted syntax!  Learned something new today.
Well if that works, great, let's do it!

I see your point on "commenting pinned version".  How about for pillow < 7
and ipyparallel let each occupy a line, then the rest which don't need
explanations group in the same line?

Could you make that change and commit?  Thank you thank you.

**Comment by gsganden** [comment]
> I see your point on "commenting pinned version".  How about for pillow < 7 and ipyparallel let each occupy a line, then the rest which don't need explanations group in the same line?

Sure. That does mean that they can't be alphabetized, which would annoy me more than extra lines because it makes it harder to see whether a particular dependency is there or not, but I can't relate to Jeremy Howard's aversion to scrolling.

I can confirm that I was able to run `pip install .` with `ipyparallel!=6.2.5` in setup.py.

**Review by philtrade — APPROVED** [review]
Thanks!

**Pull request merged**
